name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201

      - name: restore cake tool
        run: dotnet tool restore
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: run build script
        run: dotnet cake

      - run: dotnet cake --configuration debug --target cover

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
